### ISSUE TITLE
Add note that dynamic linking is unsupported on WASM

### ISSUE THREAD

**Issue by chmorgan** [bevy-cheatbook/bevy-cheatbook#135]
I'm not sure how to debug from here, looking for ideas.

```
% cargo -vv run --target wasm32-unknown-unknown

error: cannot produce dylib for `bevy_dylib v0.6.0` as the target `wasm32-unknown-unknown` does not support these crate types
```

```
% cat .cargo/config.toml 
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
```

**Comment by inodentry** [comment]
Yes, the dynamic feature is platform specific. It is only known to work well on Linux. It should work on Win/Mac too, but I've heard people have issues with it. Wasm has no dynamic linking, so ofc it is not supported there at all.

It really shouldn't be so eagerly recommended. Bevy's official "getting started" advice is quite misleading IMO. It goes very far into recommending experimental/unreliable stuff (like the dynamic feature, and using Rust Nightly with `-Z share-generics`), which you really don't need to "get started" (compile times are plenty fast as is) and these things often cause issues for many users. It also neglects mentioning issues that new users do actually commonly run into, like unusably slow performance without compiler optimizations (the [cheatbook page](https://bevy-cheatbook.github.io/pitfalls/performance.html) about this topic is one of the most often linked pages in the Bevy Discord, because *so many* people need this).

I will add a note to the cheatbook wasm page to warn people that they can't use `dynamic` on WASM. Meanwhile, if you want to contribute, your efforts would IMO be better spent on improving the info on Bevy's website. Make a PR to [bevy-website](https://github.com/bevyengine/bevy-website).

**Comment by chmorgan** [comment]
Ok. I guess I feel less qualified to propose changes there beyond maybe
linking to the cheat book with a note about wasm builds and dynamic but
even still I’m unsure.

I also ran into the optimization issue which I didn’t see mentioned in the
cheat book section for wasm, but maybe I missed it? Without optimizations
it took a minute to load and performance was terrible. With optimizations
it was 1/4 the size and ran pretty well (it’s still a simple example game).

**Comment by inodentry** [comment]
This applies to all Bevy projects, not just WASM: https://bevy-cheatbook.github.io/pitfalls/performance.html

For WASM release builds, you can additionally consider optimizing for size instead, as page load times typically depend on how fast people can download your binary: https://bevy-cheatbook.github.io/platforms/wasm/size-opt.html

**Comment by rchar-hub** [comment]
In case it's useful for people, my approach to working around this has been by using the following in my `Cargo.toml`:
```toml
[dependencies.bevy]
version = "0.6.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies.bevy]
version = "0.6.1"
# Note that the dynamic feature isn't supported for WASM targets.
# But it does speed up compilation times on other platforms.
features = ["dynamic"]

[target.'cfg(target_family = "wasm")'.profile.release]
# Optimise for size (only really useful if targeting WASM)
opt-level = "z"
```

It seems to work fairly well for just automatically handling targeting WASM, but it's a little verbose (have to specify the Bevy version twice - would be nice to avoid this) and feels a little hacky.
